rseed: 0
device: 'cpu'
# mu and sigma of prior normal distributions for the parameters
U_mu: 0
V_mu: 0
W_mu: 0
Hcategorical_mu: 0
Hpoisson_mu: 0
Hgaussian_mu: 0
U_std: 1
V_std: 1
W_std: 1
Hcategorical_std: 1
Hpoisson_std: 1
Hgaussian_std: 1
U_init_mu: 0
V_init_mu: 0
W_init_mu: 0
Hcategorical_init_mu: 0
Hpoisson_init_mu: 0
Hgaussian_init_mu: 0
U_init_std: 3
V_init_std: 3
W_init_std: 3
Hcategorical_init_std: 3
Hpoisson_init_std: 3
Hgaussian_init_std: 3
# hyperparameters for model optimization
gamma: 0.1
num_iter: 2000
lik_weight: 1
learning_rate: 0.5
tolerance: 0.00000001
verbose: False
N_seeds: 10